/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PackagingTeam;

import business.Business;
import business.Enterprise.PackagingTeamEnterprise;
import business.Organisation.Organisation;
import business.UserAccount.UserAccount;
import business.UserAccount.UserAccountDirectory;
import business.WorkQueue.WorkRequest;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uttkarsh
 */
public class SupervisorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form PackagingTeamWorkAreaJPanel
     */
    private JPanel workArea;
    private PackagingTeamEnterprise ent;
    private Business business;
    private UserAccount userAccount;
     private Image backgroundImage;
    public SupervisorWorkArea(JPanel userProcessContainer, UserAccount account, PackagingTeamEnterprise ent, Business business) {
        initComponents();
        
        this.workArea = userProcessContainer; 
    this.ent = ent;
    this.business = business;
    this.userAccount = account;
    
     try {
            backgroundImage = ImageIO.read(new File("/Users/uttkarsh/Desktop/final-project-team_titan/Final/deli.jpeg"));
        } catch (IOException e) {
            e.printStackTrace();
            // Handle the exception (e.g., log the error, show a message)
        }
    }

      @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Draw the background image
        g.drawImage(backgroundImage, 0, 0, this.getWidth(), this.getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        assigndel = new javax.swing.JButton();
        Addpackage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssignDelivery = new javax.swing.JTable();
        deliveryguy = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Packaging Team Supervisor Portal");

        assigndel.setText("Assign a Delivery");
        assigndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigndelActionPerformed(evt);
            }
        });

        Addpackage.setText("Add package to Deliver");
        Addpackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddpackageActionPerformed(evt);
            }
        });

        AssignDelivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Package", "Delivery to Unit No.", "Resident Name", "Status", "DeliveryGuy"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AssignDelivery);
        if (AssignDelivery.getColumnModel().getColumnCount() > 0) {
            AssignDelivery.getColumnModel().getColumn(0).setResizable(false);
            AssignDelivery.getColumnModel().getColumn(1).setResizable(false);
            AssignDelivery.getColumnModel().getColumn(2).setResizable(false);
            AssignDelivery.getColumnModel().getColumn(3).setResizable(false);
            AssignDelivery.getColumnModel().getColumn(4).setResizable(false);
        }

        deliveryguy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryguyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Addpackage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(assigndel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(deliveryguy, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addpackage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assigndel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryguy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddpackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddpackageActionPerformed
        // TODO add your handling code here:
          // Prompt the user for package details using JOptionPane
    String residentName = JOptionPane.showInputDialog(this, "Enter Resident Name:");
    String residentIdString = JOptionPane.showInputDialog(this, "Enter Unit No.:");
    String packageDetails = JOptionPane.showInputDialog(this, "Enter Package Details:");

    // Validate and convert Resident ID to integer
    int residentId;
    try {
        residentId = Integer.parseInt(residentIdString);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Resident ID. Please enter a valid number.");
        return; // Exit the method if the ID is invalid
    }

    // Add a new row to the table with the entered details
    DefaultTableModel model = (DefaultTableModel) AssignDelivery.getModel();
    model.setRowCount(0);
    Object[] rowData = {
        packageDetails,
        residentId,
        residentName,
        "Not Delivered",
        "Not Assigned",
    };
    model.addRow(rowData);

    // Notify user about the successful addition
    JOptionPane.showMessageDialog(this, "Package added successfully!");

    }//GEN-LAST:event_AddpackageActionPerformed

    private void deliveryguyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryguyActionPerformed
       
    }//GEN-LAST:event_deliveryguyActionPerformed

    private void assigndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigndelActionPerformed
           // Get the selected row index
    int selectedRowIndex = AssignDelivery.getSelectedRow();

    // Check if a row is selected
    if (selectedRowIndex == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to assign the delivery.");
        return;
    }

    // Get the values from the selected row
    int residentid = (int) AssignDelivery.getValueAt(selectedRowIndex, 1); // Assuming "Resident Name" is at column index 2
    String deliveryGuy = deliveryguy.getText();

    // Check if the logged-in user is the same as the entered delivery guy
   
        // Create a WorkRequest
        WorkRequest workRequest = new WorkRequest() {};
        workRequest.setMessage(String.valueOf(residentid));
        workRequest.setSender(userAccount);

        // Set the receiver based on the entered delivery guy
        UserAccount deliveryGuyAccount = null;
        
        for (Organisation org : ent.getOrganisationDirectory().getOrganisationList()) {
            for (UserAccount ur : org.getUserAccountDirectory().getUserAccountList()) {
                if (ur.getUsername().equals(deliveryGuy)) {
                    deliveryGuyAccount = ur;
                 //   System.out.print(deliveryGuyAccount);
                    break; // Exit the loop once a match is found
                }
            }
            if (deliveryGuyAccount != null) {
                break; // Exit the outer loop once a match is found
            }
        }

        if (deliveryGuyAccount != null) {
            workRequest.setReceiver(deliveryGuyAccount);
            deliveryGuyAccount.getWorkQueue().getWorkRequestList().add(workRequest);
            
            System.out.println(deliveryGuyAccount.getWorkQueue().getWorkRequestList());
        } else {
            JOptionPane.showMessageDialog(this, "Delivery guy not found.");
            return;
        }

        workRequest.setStatus("In-Transit");
        workRequest.setType("Delivery Assignment");

        // Add the WorkRequest to your business or the appropriate data structure
        // business.addWorkRequest(workRequest);

        // Update the "DeliveryGuy" column in the selected row
        AssignDelivery.getModel().setValueAt(deliveryGuy, selectedRowIndex, 4); // Assuming "DeliveryGuy" is at column index 4

        // Notify the user about the successful assignment
        JOptionPane.showMessageDialog(this, "Delivery assigned successfully!");
    
    }//GEN-LAST:event_assigndelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addpackage;
    private javax.swing.JTable AssignDelivery;
    private javax.swing.JButton assigndel;
    private javax.swing.JTextField deliveryguy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

 
   


}
